/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:4da2d4ba-8e2a-4bec-b32e-666ccce7adae",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_7otVSaCnJ",
    "aws_user_pools_web_client_id": "2vjlmor5ia00ldgbm9be6b0jm3",
    "oauth": {}
};


export default awsmobile;
